### ISSUE TITLE
Update to RestrictedPython >= 4 and Python 3

### ISSUE THREAD

**Issue by icemac** [zopefoundation/zope.untrustedpython#2]
Currently this package is not compatible with RestrictedPython >= 4.

cc: @loechel Do I remember correctly that you have already worked on this issue?

**Comment by loechel** [comment]
@icemac yes, I have already looked into this package, a few years ago. Due to the time I did not remember all, but might could look quickly into it, again over the holidays.

**Comment by icemac** [comment]
There is https://github.com/zopefoundation/zope.untrustedpython/tree/Python3_update which contains the current state of the porting work.

**Comment by realnickel** [comment]
Hello!
Are there any plans to release this update in the nearest future?

**Comment by icemac** [comment]
@realnickel I put this issue on my list for [Alpine City Sprint](https://alpinecity.tirol/2020) in February.
Until then a PR is welcome, too.

**Comment by icemac** [comment]
I did not manage to fix this issue on Alpine City Sprint, maybe on [Zope May remote sprint](https://www.meetup.com/de-DE/Zope-Sprint/events/269031661/) in May.

**Comment by jugmac00** [comment]
@icemac so this package should be supported? Maybe you can have a look at the test suite, which is failing for over a year.

**Comment by mgedmin** [comment]
zope.untrustedpython is a conditional depqendency of zope.pagetemplate and zope.security.  In both cases it's only installed under Python 2.7, and only if explicitly requested by depending on `zope.pagetemplate[untrusted]`/`zope.security[untrustedpython]`.

z3c.zrtresource does that (depend on `zope.security[untrustedpython]`), and nothing else in the ZopeFoundation/ namespace on GitHub.

**Comment by jugmac00** [comment]
Thank you for the information!

**Comment by icemac** [comment]
As `RestrictedPython` is ported to Python 3 `zope.untrustedpython` should use it for Python 3, too and consumers, should do so, too. (Currently they are using standard Python `eval` resp. `exec` without any restrictions tu run untrusted code … that's not good.)

**Comment by jugmac00** [comment]
> As `RestrictedPython` is ported to Python 3 `zope.untrustedpython` should use it for Python 3, too and consumers, should do so, too. (Currently they are using standard Python `eval` resp. `exec` without any restrictions tu run untrusted code … that's not good.)

@icemac Can you clarify? Does this mean that currently `RestrictedPython` does not restrict anything? Or what does this mean?
