### ISSUE TITLE
build is failing

### ISSUE THREAD

**Issue by jugmac00** [zopefoundation/zope.untrustedpython#4]
https://travis-ci.org/github/zopefoundation/zope.untrustedpython

**Comment by mgedmin** [comment]
Whee, Travis is running python setup.py -q test, which fails for reasons I don't care about.

First step, modernize everything so we can use tox + zope.testrunner.  Then we can see if there are real failures.

**Comment by jamadden** [comment]
>  we can use tox + zope.testrunner

Why do we want the extra messiness of wrapping everything in tox (i.e., a duplicate virtual environment)? I've been *removing* calls to tox from .travis.yml for years and just inlining the call to the testrunner; it may be a repetition, but it's one trivial line.

If this was discussed somewhere, I missed it and would appreciate any pointers to the discussion.

**Comment by mgedmin** [comment]
> If this was discussed somewhere, I missed it and would appreciate any pointers to the discussion.

There's a bunch of PRs that use automation from https://github.com/zopefoundation/meta/tree/master/config.  I don't remember this being discussed beforehand, but I don't mind.

I don't personally insist on tox being called from .travis.yml (although I like it for DRY reasons), I just want a tox.ini for local development.

**Comment by mgedmin** [comment]
I seem to have reached the stage where I can't form coherent sentences any more.

My point was, zopefoundation/meta is probably the right forum to discuss the decision to standartize on tox-travis.

**Comment by jugmac00** [comment]
As I am not super familiar with zope.testrunner, when I see a package like this, I try to run it locally with pytest, as I think it has pretty good test discovery, and after 5 minutes I gave up because of import errors.

Is this package used by anybody at all? I see no reason to fix builds for its own sake, but only when there is somebody out relying on this package.

**Comment by mgedmin** [comment]
Well, you opened this issue giving us the impression that you care about tests failing :)

It's probably best to continue discussing whether this package should be supported or not in https://github.com/zopefoundation/zope.untrustedpython/issues/2#issuecomment-628691726, instead of splitting the discussion across two issues.

**Comment by jugmac00** [comment]
Sorry for the wrong impression.

As of today's sprint I just went through all repositories which had a failing build and tried to fix them, or if not able to, create an issue.

**Comment by icemac** [comment]
Fixed in #5.
